version: '3'

services:
  message-service:
    image: message-service:latest
    container_name: message-service

  user-service:
    image: user-service:latest
    container_name: user-service
    command:
      - "--mysql.address=172.27.160.34"

  user-edge-service:
    image: user-edge-service:latest
    container_name: user-edge-service
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=172.27.160.34"

  course-service:
    image: course-service:latest
    container_name: course-service
    links:
      - user-service
    command:
      - "--mysql.address=172.27.160.34"
      - "--zookeeper.address=172.27.160.34"

  course-edge-service:
    image: course-edge-service:latest
    container_name: course-edge-service
    links:
      - user-edge-service
    command:
      - "--zookeeper.address=172.27.160.34"

  api-agetway-zuul:
    image: api-gateway-zuul:latest
    container_name: api-agetway-zuul
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 8085:8085