version: "3.4"
services:
  message-service:
    image: 172.27.160.34:8090/micro-service/message-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"

  user-service:
    image: 172.27.160.34:8090/micro-service/user-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    command:
      - "--mysql.address=172.27.160.34"

  user-edge-service:
    image: 172.27.160.34:8090/micro-service/user-edge-service:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - message-service
    command:
      - "--redis.address=172.27.160.34"

  course-service:
    image: 172.27.160.34:8090/micro-service/course-service:latest
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    depends_on:
      - user-service
    command:
      - "--mysql.address=172.27.160.34"
      - "--zookeeper.address=172.27.160.34"


  course-edge-service:
    image: 172.27.160.34:8090/micro-service/course-edge-service:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "8084:8084"
    depends_on:
      - user-edge-service
    command:
      - "--zookeeper.address=172.27.160.34"

  api-gateway-zuul:
    image: 172.27.160.34:8090/micro-service/api-gateway-zuul:latest
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    ports:
      - "8085:8085"
    depends_on:
      - user-edge-service
      - course-edge-service

networks:
  default:
    external:
      name: xujun-overlay
